name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test branch-name
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: Run branch-name
        uses: ./
        continue-on-error: true
